"use strict";

const ENGLISH_TEXT = {
  "Aller au jeu":"Skip to game",
  "Deux mille miles de poussière, de rivières et de choix difficiles. Conduirez-vous votre famille jusqu’à la vallée de Willamette ?":"Two thousand miles of dust, rivers, and difficult choices. Can you lead your family to the Willamette Valley?",
  "Prendre la piste":"Hit the trail",
  "Lire le guide du pionnier":"Read the pioneer guide",
  "Infos sur le projet":"About this project",
  "La piste ne vous attendra pas : préparez-vous avant de partir.":"The trail will not wait: prepare before you leave.",
  "Independence, Missouri · Printemps 1848":"Independence, Missouri · Spring 1848",
  "Pionnier, ce que tu sais avant le départ":"Pioneer, what you know before leaving",
  "Les récits venus de l’Oregon se contredisent, mais tous s’accordent sur un point : la piste récompense les convois prévoyants.":"Stories from Oregon contradict one another, but they all agree on one thing: the trail rewards well-prepared wagon parties.",
  "Deux mille miles vers l’ouest":"Two thousand miles west",
  "Tu traverseras des plaines sans fin, des forts isolés, des montagnes et plusieurs grands fleuves. Le temps, la fatigue et les détours consommeront plus que prévu. Aucun chargement ne protège de tout : il faut choisir ce que tu es prêt à risquer.":"You will cross endless plains, isolated forts, mountains, and several great rivers. Time, exhaustion, and detours will consume more than expected. No loadout protects against everything: choose what you are willing to risk.",
  "Dans le chariot":"In the wagon",
  "Ce que chaque provision peut sauver":"What each supply can save",
  "Bœufs":"Oxen","Vivres":"Food","Munitions":"Ammunition","Couvertures":"Blankets","Pièces de rechange":"Spare parts","Remèdes":"Medicine","Argent":"Money",
  "Ils déterminent l’allure du convoi. Une équipe nombreuse tire mieux dans la boue et les pentes. Un animal peut se blesser, se perdre dans un fleuve ou devoir être abattu pour sa viande. Sans bœuf, le voyage s’arrête.":"They determine the wagon party’s pace. A large team pulls better through mud and slopes. An animal may be injured, lost in a river, or slaughtered for meat. Without an ox, the journey ends.",
  "Chaque bouche mange chaque jour, même lorsque le chariot attend une réparation ou la baisse des eaux. La chasse peut refaire les réserves, mais elle n’est ni facile ni garantie.":"Every person eats every day, even while the wagon waits for repairs or lower water. Hunting can replenish supplies, but it is neither easy nor guaranteed.",
  "Les balles servent surtout à la chasse. Les petits animaux sont rapides et le gros gibier rare : une caisse pleine ne promet pas un garde-manger plein. Sous la pluie, les bisons se montrent moins souvent ; dans la neige, tout le gibier se raréfie.":"Bullets are mostly used for hunting. Small animals are fast and big game is rare: a full ammunition box does not promise a full pantry. Bison appear less often in rain, and all game becomes scarce in snow.",
  "Une couverture protège une personne du froid et de l’humidité. Elles s’usent, se détrempent et peuvent être volées ou emportées par l’eau. Ceux qui passent une nuit froide sans protection s’affaiblissent vite et risquent les engelures.":"One blanket protects one person from cold and damp. Blankets wear out, become soaked, and may be stolen or swept away. Anyone facing a cold night without protection weakens quickly and risks frostbite.",
  "Une roue, un essieu ou un timon peut céder loin de toute forge. Une pièce épargne des jours d’improvisation et évite de sacrifier une partie du chargement.":"A wheel, axle, or wagon tongue may fail far from a forge. A spare part saves days of improvisation and avoids sacrificing part of the load.",
  "Bandages, alcool, sels et fortifiants donnent une chance aux fièvres, aux blessures et aux maladies contagieuses. Un voyageur déjà très affaibli peut ne pas survivre sans soins. Les remèdes peuvent aussi aider à remettre un bœuf sur pied.":"Bandages, alcohol, salts, and tonics give travelers a chance against fevers, wounds, and contagious disease. An already weakened traveler may not survive without care. Medicine may also help an ox recover.",
  "Les forts vendent parfois ce qui te manque, mais plus tu avances, plus les prix montent. Les bacs, réparations urgentes et rencontres sur la piste exigent souvent des espèces.":"Forts sometimes sell what you need, but prices rise as you travel west. Ferries, urgent repairs, and encounters on the trail often demand cash.",
  "Sur la piste":"On the trail","Allure et rations":"Pace and rations","Le calendrier":"The calendar","Partir au bon moment":"Leave at the right time","Aux fleuves":"At the rivers","Ne sous-estime jamais l’eau":"Never underestimate the water","Ce que les récits taisent":"What the stories leave out","L’imprévu voyage avec toi":"The unexpected travels with you",
  "Presser les bœufs fait gagner du terrain, mais le rythme épuisant augmente nettement la consommation, les blessures, les avaries et le risque de voir un bœuf céder. Même une étape sans accident laisse alors des traces. Des rations maigres prolongent les sacs au prix de voyageurs plus fragiles. Se reposer coûte du temps et des vivres, mais soulage aussi l’attelage.":"Driving the oxen gains ground, but a grueling pace sharply increases consumption, injuries, breakdowns, and the chance of an ox collapsing. Even an uneventful leg then takes its toll. Meager rations stretch the food bags at the cost of weaker travelers. Rest consumes time and food, but also relieves the team.",
  "Un convoi bien mené espère atteindre l’Oregon en quatre à six mois. Mars offre du temps mais expose au froid. Mai promet des débuts plus doux, avec moins de marge avant l’hiver. Le temps change rarement d’un extrême à l’autre en une nuit et dépend du pays traversé : les bassins désertiques restent secs, les cols sont plus froids et la Columbia plus humide. La pluie, la chaleur et la neige ralentissent les roues. Les montées, les descentes et une piste dégradée peuvent réduire encore davantage l’allure.":"A well-run wagon party can hope to reach Oregon in four to six months. March offers time but exposes you to cold. May promises a milder start, with less room before winter. Weather rarely swings from one extreme to another overnight and depends on the country crossed: desert basins stay dry, passes are colder, and the Columbia is wetter. Rain, heat, and snow slow the wheels. Climbs, descents, and a poor trail may reduce the pace even further.",
  "Le bac coûte cher mais protège généralement le chargement. Le niveau varie avec la saison, la pluie, la fonte des neiges et les caprices du courant. Attendre consomme des jours et des vivres sans garantir une baisse : après trois jours, l’eau peut aussi avoir monté. Faire flotter le chariot économise l’argent, au risque de perdre provisions, équipement ou bœufs dans le courant.":"The ferry is expensive but usually protects the load. Water levels vary with the season, rain, snowmelt, and the current. Waiting consumes days and food without guaranteeing lower water: after three days it may have risen. Floating the wagon saves money, at the risk of losing food, equipment, or oxen.",
  "Vols, essieux brisés, animaux blessés, dysenterie, fièvre et rencontres commerciales peuvent changer les priorités en une journée. Les forts ne possèdent pas toujours l’article recherché. Garde une réserve et adapte-toi.":"Theft, broken axles, injured animals, dysentery, fever, and trading encounters can change priorities in a day. Forts do not always stock what you need. Keep a reserve and adapt.",
  "« Charge ce dont tu auras besoin, puis garde encore un peu de place pour ce que tu n’as pas prévu. »":"“Pack what you will need, then leave a little room for what you did not foresee.”",
  "Conseil entendu chez Matt, marchand général":"Advice heard at Matt’s General Store","Retour":"Back","Avant le grand départ":"Before the great departure","Qui prend la piste ?":"Who is taking the trail?","Votre métier détermine votre bourse et votre expérience.":"Your occupation determines your funds and experience.","Votre métier":"Your occupation","Fermier":"Farmer","800 $ · Bonus de score":"$800 · Score bonus","Charpentier":"Carpenter","1 000 $ · Répare mieux":"$1,000 · Better repairs","Banquier":"Banker","1 600 $ · Voyage plus facile":"$1,600 · Easier journey","Les cinq voyageurs":"The five travelers","Chef de convoi":"Wagon leader","Compagnon":"Companion","Voyageur":"Traveler","Mois de départ":"Departure month","Mars":"March","Plus de temps, froid mordant":"More time, biting cold","Avril":"April","Le choix équilibré":"The balanced choice","Mai":"May","Temps doux, hiver proche":"Mild weather, winter closer","Préparer le chariot":"Prepare the wagon",
  "Chez Matt, marchand général":"Matt’s General Store","Chargez soigneusement":"Pack carefully","Une fois parti, les prix augmenteront à chaque fort.":"Once you leave, prices will rise at every fort.","Le chariot est vide : c’est à vous de composer entièrement le chargement.":"The wagon is empty: you must build the entire loadout yourself.","Votre bourse":"Your funds","Quitter Independence":"Leave Independence","Guide du pionnier":"Pioneer guide","Modifier le groupe":"Change the party",
  "Rythme":"Pace","Prudent — ménage le convoi":"Steady — spare the party","Soutenu — équilibré":"Strenuous — balanced","Épuisant — risques élevés":"Grueling — high risk","Rations":"Rations","Copieuses":"Filling","Normales":"Normal","Maigres":"Meager","Voyager 5 jours":"Travel 5 days","Chasser":"Hunt","Se reposer":"Rest","Carte":"Map","Inventaire":"Inventory","Chariot":"Wagon","Pièces":"Parts","Le groupe":"The party","Bonne santé":"Good health","Journal de bord":"Trail journal","Tout voir":"View all","Vallée de Willamette":"Willamette Valley","Vous avez atteint l’Oregon":"You reached Oregon","Votre réussite":"Your achievement","Pionnier ordinaire":"Ordinary pioneer","Reprendre la piste":"Return to the trail","Un événement":"An event",
  "Les grandes plaines":"The Great Plains","Chasse":"Hunt","Visez avec la souris, les flèches ou en touchant l’animal, puis tirez avec clic, toucher ou Espace. Chaque tir coûte une balle.":"Aim with the mouse, arrow keys, or by touching an animal, then shoot with a click, tap, or Space. Every shot costs one bullet.","Temps":"Time","Butin":"Game","Balles":"Bullets","Retour au camp":"Back at camp","Bilan de la chasse":"Hunt report","Balles tirées":"Bullets fired","Balles restantes":"Bullets left","Viande chargée":"Meat loaded","L’autre rive":"The far bank","Bilan de la traversée":"Crossing report","Méthode":"Method","Bac":"Ferry","Durée":"Duration","1 jour":"1 day","Vivres consommés":"Food consumed",
  "Alerte sur la piste":"Trail alert","Protégez le convoi":"Protect the wagon party","Déplacez le chariot avec les flèches gauche et droite. Évitez les projectiles jusqu’à la fin de l’attaque.":"Move the wagon with the left and right arrows. Avoid the projectiles until the attack ends.","Impacts":"Hits","← Gauche":"← Left","Droite →":"Right →","Le calme revient":"Calm returns","Bilan de l’attaque":"Attack report","Blessés":"Wounded","Décès":"Deaths","Utiliser des remèdes":"Use medicine","Fermer":"Close",
  "Doux":"Mild","Chaud":"Hot","Pluvieux":"Rainy","Froid":"Cold","Neige":"Snow","Fatigué":"Tired","Très faible":"Very weak","Décédé":"Dead","Blessé":"Injured","Convalescent":"Recovering","Fièvre":"Fever","Dysenterie":"Dysentery","Engelures":"Frostbite","Piqûres":"Bites","Malade":"Sick",
  "Rivière Kansas":"Kansas River","Rivière Snake":"Snake River","Vallée de Willamette":"Willamette Valley","Prairies du Kansas":"Kansas Prairies","Les Grandes Plaines":"The Great Plains","Le pays de la Platte":"Platte country","Les Rocheuses":"The Rocky Mountains","Le pays de l’Oregon":"Oregon Country","les Grandes Plaines":"the Great Plains","la vallée de la Platte":"the Platte Valley","les Rocheuses":"the Rocky Mountains","le pays de l’Oregon":"Oregon Country","temps pluvieux":"rainy weather","temps froid":"cold weather","temps froid et enneigé":"cold, snowy weather","temps chaud et aride":"hot, dry weather","temps modéré":"mild weather",
  "Disparu sans laisser de trace":"Vanished without a trace","Nourriture pour coyotes":"Coyote food","Victime de la dysenterie":"Dysentery victim","Conducteur de chariot égaré":"Lost wagon driver","Pionnier mal préparé":"Ill-prepared pioneer","Chercheur d’or bredouille":"Empty-handed gold seeker","Voyageur du dimanche":"Sunday traveler","Convoyeur de bétail":"Cattle drover","Éclaireur hésitant":"Hesitant scout","Chef de famille prudent":"Prudent family leader","Guide de convoi":"Wagon train guide","Vétéran de la piste":"Trail veteran","Bâtisseur de ferme":"Farm builder","Fondateur de comptoir":"Trading post founder","Capitaine de la Frontière":"Frontier captain","Maître de la piste de l’Oregon":"Master of the Oregon Trail","Conquérant de l’Ouest":"Conqueror of the West","Légende de la Frontière":"Frontier legend","Père ou Mère de l’Oregon":"Father or Mother of Oregon",
  "bête":"ox","bêtes":"oxen","balle":"bullet","balles":"bullets","pièce":"item","pièces":"items","dose":"dose","doses":"doses",
  "Une paire coûte 40 $. Il en faut au moins quatre.":"A pair costs $40. You need at least four.","Farine, lard, café et haricots. Prix pour 10 kg.":"Flour, bacon, coffee, and beans. Price per 10 kg.","Boîtes de 20 balles pour la chasse.":"Boxes of 20 bullets for hunting.","Chacune protège un voyageur du froid et de l’humidité.":"Each protects one traveler from cold and damp.","Roues, essieux et timons pour les avaries.":"Wheels, axles, and wagon tongues for breakdowns.","Bandages et fortifiants pour soigner le groupe.":"Bandages and tonics to treat the party.",
  "Il faut au moins 4 bœufs.":"You need at least 4 oxen.","Prévoyez environ 400 kg de vivres.":"Plan for about 400 kg of food.","Prévoyez au moins 100 balles pour la chasse.":"Plan for at least 100 bullets for hunting.","Votre chargement semble prêt pour la piste.":"Your load seems ready for the trail.",
  "Une étape sans incident":"An uneventful leg","Poursuivre la route":"Continue on the trail","Une étape calme et sans incident.":"A quiet, uneventful leg.","Les vivres sont épuisés. La faim affaiblit tout le monde.":"The food is gone. Hunger weakens everyone.","La piste a eu raison de tout le convoi.":"The trail has claimed the entire party.","Nous avons quitté Independence. La piste s’ouvre devant nous.":"We left Independence. The trail opens before us.",
  "Réparer et repartir":"Repair and leave","La fièvre":"Fever","Un remède améliore nettement ses chances.":"Medicine greatly improves the odds.","Utiliser un remède":"Use medicine","Continuer prudemment":"Continue carefully","Essieu brisé":"Broken axle","Un choc sec — l’essieu du chariot vient de céder.":"A sharp crack—the wagon axle has just broken.","Effectuer la réparation":"Make the repair","Votre essieu est rompu et vous n’avez aucune pièce.":"Your axle is broken and you have no spare part.","Une famille de passage propose une pièce pour 45 $.":"A passing family offers a spare part for $45.","Acheter la pièce (45 $)":"Buy the part ($45)","Alléger et improviser":"Lighten the load and improvise","Une bonne rencontre":"A fortunate encounter","Des voyageurs revenant de l’Oregon partagent leurs provisions.":"Travelers returning from Oregon share their supplies.","Les remercier":"Thank them","Une famille généreuse nous a ravitaillés.":"A generous family resupplied us.",
  "Pluies diluviennes":"Torrential rain","La boue avale les roues. Impossible d’avancer.":"The mud swallows the wheels. Moving forward is impossible.","Attendre l’éclaircie":"Wait for clear skies","Un bœuf blessé":"An injured ox","Une pierre a fait chuter l’un des bœufs. Sa patte enflée ne supporte plus le joug.":"A stone has brought down one of the oxen. Its swollen leg can no longer bear the yoke.","C’est votre dernier bœuf. L’abattre laisserait le chariot sans attelage.":"This is your last ox. Slaughtering it would leave the wagon without a team.","Vous pouvez tenter de le soigner ou transformer l’animal en provisions.":"You may try to treat it or turn the animal into food.","Le soigner et attendre 2 jours":"Treat it and wait 2 days",
  "Blessure sur la piste":"Injury on the trail","Poser une attelle":"Apply a splint","Dysenterie":"Dysentery","Donner un remède":"Give medicine","Faire halte 2 jours":"Stop for 2 days","Continuer":"Continue","Engelures":"Frostbite","Piqûres d’insectes":"Insect bites","Il faut réchauffer progressivement les zones atteintes.":"The affected areas must be warmed gradually.","Les piqûres se sont infectées et doivent être nettoyées.":"The bites are infected and must be cleaned.","Réchauffer et attendre":"Warm up and wait","Nettoyer et repartir":"Clean the wounds and leave","Maladie contagieuse":"Contagious disease","Isoler les malades 2 jours":"Isolate the sick for 2 days","Continuer la route":"Continue on the trail","Le convoi s’est arrêté pour isoler les malades.":"The wagon party stopped to isolate the sick.","La maladie contagieuse affaiblit le groupe.":"The contagious disease weakens the party.","Couvertures hors d’usage":"Ruined blankets","Une nuit glaciale et humide détrempe les couvertures les plus exposées.":"A freezing, damp night soaks the most exposed blankets.","Réorganiser le chargement":"Rearrange the load",
  "Tentative de vol":"Attempted theft","Des traces entourent le camp, mais le chargement est intact.":"Tracks surround the camp, but the load is intact.","Les coffres étaient heureusement vides ou bien verrouillés.":"Fortunately, the chests were empty or securely locked.","Redoubler de vigilance":"Be more vigilant","Une tentative de vol a échoué.":"An attempted theft failed.","Vol au camp":"Theft at camp","Au lever du jour, un coffre est ouvert et des traces s’éloignent du camp.":"At daybreak, a chest is open and tracks lead away from camp.","Sécuriser le chargement":"Secure the load","Une proposition sur la piste":"An offer on the trail","La quantité et le prix sont fixes. Acceptez-vous l’offre ?":"The quantity and price are fixed. Do you accept the offer?","Accepter":"Accept","Refuser":"Decline","Nous avons refusé une proposition commerciale.":"We declined a trade offer.",
  "Attaque du convoi":"Attack on the wagon party","Les indiens approchent rapidement à cheval et des projectiles frappent autour des chariots.":"The Indians approach quickly on horseback as projectiles strike around the wagons.","Mettez le groupe à couvert et tenez jusqu’à leur retrait.":"Get the party under cover and hold out until they withdraw.","Protéger le convoi":"Protect the wagon party","Un repère bienvenu sur l’immensité de la piste.":"A welcome landmark in the vastness of the trail.","Graver nos noms et repartir":"Carve our names and leave","Comment ferez-vous traverser le chariot ?":"How will you get the wagon across?","Calfater et flotter":"Caulk and float","Attendre 3 jours et remesurer":"Wait 3 days and measure again","Chariot calfaté":"Caulked wagon","Le bac a transporté le chariot et tout le groupe jusqu’à l’autre rive.":"The ferry carried the wagon and the entire party to the far bank.","Le chariot a pris l’eau dans le courant avant d’atteindre difficilement l’autre rive.":"The wagon took on water in the current before struggling to the far bank.","Le chariot a flotté jusqu’à l’autre rive sous le contrôle des cordes et des bœufs.":"The wagon floated to the far bank under the control of ropes and oxen.","Le courant a secoué le convoi.":"The current battered the wagon party.",
  "Palissades, forge et odeur de pain frais : une halte bienvenue.":"Palisades, a forge, and the smell of fresh bread: a welcome stop.","Le stock d’équipement varie à chaque fort. Vous pouvez effectuer plusieurs achats avant de repartir.":"Equipment stock varies at every fort. You may make several purchases before leaving.","Se reposer 2 jours":"Rest for 2 days","Repartir":"Leave","Pas assez de vivres pour camper deux jours.":"Not enough food to camp for two days.","Deux jours de repos ont remonté le moral du groupe et soulagé l’attelage.":"Two days of rest lifted the party’s spirits and relieved the oxen.",
  "Inventaire du chariot":"Wagon inventory","Argent restant":"Money left","Le chariot transporte aussi vos outils, de la vaisselle et les souvenirs du voyage.":"The wagon also carries your tools, cookware, and memories of the journey.","Carte de la piste":"Trail map","Vous êtes ici":"You are here","La piste s’arrête ici":"The trail ends here","Vallée de Willamette · Oregon":"Willamette Valley · Oregon","Vous avez atteint l’Oregon":"You reached Oregon","Le convoi n’ira pas plus loin":"The wagon party will go no farther","La faim, la maladie et la route ont eu raison de votre expédition.":"Hunger, disease, and the road have defeated your expedition.","Aucune entrée dans le journal.":"No entries in the journal.","Vous n’avez plus de munitions.":"You are out of ammunition.","Le chariot ne peut pas charger davantage de vivres.":"The wagon cannot carry any more food.","Touché":"Hit","Aucune victime":"No casualties","Le convoi a tenu bon.":"The wagon party held firm.","Aucun remède nécessaire":"No medicine needed","Aucun remède disponible":"No medicine available","État critique":"Critical condition","Blessure légère":"Minor injury","Sérieusement affaibli":"Seriously weakened","Aucun membre du convoi n’a survécu à l’attaque.":"No member of the wagon party survived the attack.","Donnez un nom à chaque voyageur.":"Give every traveler a name.","Vous n’avez pas assez d’argent.":"You do not have enough money.","Il vous faut au moins quatre bœufs.":"You need at least four oxen.","Emportez au moins 100 kg de vivres.":"Take at least 100 kg of food.","Le dernier bœuf ne peut plus tirer. Sans attelage, le chariot reste abandonné sur la piste.":"The last ox can no longer pull. Without a team, the wagon is abandoned on the trail."
};

const ENGLISH_ARIA = {
  "Un chariot traverse les grandes plaines vers les montagnes":"A wagon crosses the Great Plains toward the mountains",
  "Conseils de voyage":"Travel advice","Afficher l’aide":"Show help","Progression vers l’Oregon":"Progress toward Oregon","Le chariot avance sur la piste":"The wagon travels along the trail","Mini-jeu de chasse":"Hunting mini-game","Un troupeau de bisons dans les grandes plaines":"A herd of bison on the Great Plains","Le convoi termine la traversée du fleuve":"The wagon party completes the river crossing","Mini-jeu d’attaque : déplacer le chariot pour éviter les projectiles":"Attack mini-game: move the wagon to avoid projectiles","Le convoi pris dans un affrontement sur la piste":"The wagon party caught in a clash on the trail","Fermer":"Close"
};

const storedLanguage=localStorage.getItem("oregon-vibe-language");
let currentLanguage=storedLanguage==="fr"||storedLanguage==="en"?storedLanguage:(/^fr\b/i.test(navigator.language)?"fr":"en");
const staticTextNodes=[];
const staticAttributes=[];

function bilingual(fr,en){return {fr,en}}
function languageText(value,language=currentLanguage){
  if(value&&typeof value==="object"&&"fr" in value)return value[language]??value.fr;
  const text=String(value??"");
  return language==="en"?(ENGLISH_TEXT[text.replace(/\s+/g," ").trim()]??text):text;
}
function bilingualJoin(left,separator,right){return bilingual(`${languageText(left,"fr")}${separator}${languageText(right,"fr")}`,`${languageText(left,"en")}${separator}${languageText(right,"en")}`)}
function currentLocale(){return currentLanguage==="en"?"en-US":"fr-FR"}

function captureStaticLanguage(){
  const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
  let node;
  while((node=walker.nextNode())){
    if(!node.nodeValue.trim()||node.parentElement?.closest("script,style"))continue;
    staticTextNodes.push({node,fr:node.nodeValue});
  }
  document.querySelectorAll("[aria-label]").forEach(element=>staticAttributes.push({element,attribute:"aria-label",fr:element.getAttribute("aria-label")}));
}

function applyStaticLanguage(){
  for(const entry of staticTextNodes){
    if(currentLanguage==="fr"){entry.node.nodeValue=entry.fr;continue;}
    const trimmed=entry.fr.trim(),translated=languageText(trimmed,"en");
    entry.node.nodeValue=translated===trimmed?entry.fr:entry.fr.replace(trimmed,translated);
  }
  for(const entry of staticAttributes)entry.element.setAttribute(entry.attribute,currentLanguage==="en"?(ENGLISH_ARIA[entry.fr]??entry.fr):entry.fr);
  document.documentElement.lang=currentLanguage;
  document.querySelector('meta[name="description"]').content=currentLanguage==="en"?"Oregon Vibe, a survival adventure on the Oregon Trail, playable entirely in your browser.":"Oregon Vibe, une aventure de survie sur la piste de l'Oregon, jouable entièrement dans le navigateur.";
  document.querySelectorAll("[data-language]").forEach(button=>button.setAttribute("aria-pressed",String(button.dataset.language===currentLanguage)));
  document.querySelector("#language-switch").setAttribute("aria-label",currentLanguage==="en"?"Choose language":"Choisir la langue");
  document.querySelector("#infos-projet").href=currentLanguage==="en"?"https://nkeywal.github.io/oregon/REQUEST-HISTORY.html":"https://nkeywal.github.io/oregon/HISTORIQUE-DEMANDES.html";
}

function setLanguage(language){
  currentLanguage=language==="en"?"en":"fr";
  localStorage.setItem("oregon-vibe-language",currentLanguage);
  applyStaticLanguage();
  window.refreshGameLanguage?.();
}

captureStaticLanguage();
applyStaticLanguage();
document.querySelectorAll("[data-language]").forEach(button=>button.addEventListener("click",()=>setLanguage(button.dataset.language)));
